ALTER TABLE users
  ADD COLUMN first_name VARCHAR(100) NOT NULL DEFAULT '' AFTER job_title,
  ADD COLUMN last_name VARCHAR(100) NOT NULL DEFAULT '' AFTER first_name,
  ADD COLUMN phone VARCHAR(40) NOT NULL DEFAULT '' AFTER last_name,
  ADD COLUMN work_hours VARCHAR(120) NOT NULL DEFAULT '' AFTER phone;